#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

start_service(){
	procd_open_instance
	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param stdout 1
	procd_set_param command /usr/bin/clash -d /etc/clash
	procd_close_instance
	# Firewall
	/etc/clash/clash-tproxy start
	echo "Clash started."
}

stop_service(){
	# Firewall
	/etc/clash/clash-tproxy stop
	killall -q clash
	echo "Clash stopped."
}
